version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: recipe_db_test
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - recipe-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./recipe-management-api-version_one
    container_name: backend-container
    ports:
      - "8090:8090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/recipe_db_test
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - recipe-network

  frontend:
    build:
      context: ./recipe-management-view-master
    container_name: frontend-container
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - recipe-network

volumes:
  db_data:

networks:
  recipe-network:
    driver: bridge
